### ISSUE TITLE
not drawing until resize

### ISSUE THREAD

**Issue by dkwebtec** [literallycanvas/literallycanvas#195]
Hello,

I have a issue with my LC.

After page load I see toolbar but drawing doesn't work. When I resize window (maximizing Chrome on Win) or rotate display (iPad) it starts to work.

Also loadSnapshotJSON appears after resize.

What am I doing wrong?

thanks

Dan

**Comment by Opendarasa** [comment]
Hi there ,
I'm having the same problem .
What was your solution? taking out the fadein main div ? 

Would very much appreciate your help ?

**Comment by edilsonborges** [comment]
For anyone that still not figure it out. For us the problem was width and height equals to 0.
In our case there were 2 canvas rendering and both of them was set to zero, so we've added the dimension after the initialization. It's not a very pleasing solution, but it worked:

var canvas = document.getElementsByTagName('canvas')[0];
canvas.width  = 1293;
canvas.height = 477;
canvas.style.width  = '1293px';
canvas.style.height  = '477px';
var canvas2 = document.getElementsByTagName('canvas')[1];
canvas2.width  = 1293;
canvas2.height = 477;       
canvas2.style.width  = '1293px';
canvas2.style.height  = '477px';
