### ISSUE TITLE
pointerdown, pointerup, pointerdrag, pointermove events

### ISSUE THREAD

**Issue by 178620086** [literallycanvas/literallycanvas#292]
i see the script have some event but not in the api doc  http://literallycanvas.com/api/events.html
so i want to know  what the event is add in new version 0.4.4 ?

<pre lang="js">
    unsubscribeFuncs.push(lc.on('pointerdown', onDown));
    unsubscribeFuncs.push(lc.on('pointerdrag', onMove));
    unsubscribeFuncs.push(lc.on('pointermove', onMove));
</pre>

 and the didBecomeActive is what time to use ?
<pre>

 # lifecycle: tool was just activated
  didBecomeActive: (lc) ->
    # subscribe to events here

  # lifecycle: tool is being deactivated
  willBecomeInactive: (lc) ->
    # unsubscribe from events here

</pre>

last i'm from china so the English not good .
but your project is very good .
thank for you reply.

**Comment by irskep** [comment]
No problem about your English. :-)

Those new events aren't released yet! They are just in the development version. If you like, you can use the development version, since it is reliable right now. I will try to do a release soon.

I'm sorry for giving you confusing advice earlier. I will edit this issue so it is something I can act on for the next release.
