### ISSUE TITLE
refreshing page causes background image not to load

### ISSUE THREAD

**Issue by jess** [literallycanvas/literallycanvas#431]
When using a background image, and I refresh the page, the background image won't load. However, if you do a normal get request to the page (via click or address bar, it works fine).

http://literallycanvas.com/examples/images.html#as-the-background

Here's a demo:

https://goo.gl/Yqr3tO

*\* It appears to affect the image a part of the drawing too. Watermark doesn't seem affected. I'm also experiencing same results in my app.

**Comment by irskep** [comment]
The demo link doesn't work anymore. Please put something on glitch or jsfiddle and I'll take a look.

I wonder if the `onload` callback for the image isn't getting called  due to caching? But that's accounted for explicitly, so I really don't know.

I'll reopen if there's another report or a code sample.
