### ISSUE TITLE
Literally Canvas NPM Update

### ISSUE THREAD

**Issue by ahad122** [literallycanvas/literallycanvas#463]
Tried doing 'npm update' but the library does not get updated. Might be an issue with the npm repo? Any help is greatly appreciated. Thanks!

Issue: http://puu.sh/w6U7v/58955adcdd.png

**Comment by irskep** [comment]
It looks like you have not installed React already. It is a "peer dependency," which means that the literallycanvas package does not directly require it.

Also, FYI I haven't done a release in a while but a few bug fix PRs have been merged, so you might need to point at the master branch instead of npm for a while.

**Comment by ahad122** [comment]
The version of react this is dependent on is out of data. I currently have React 15 installed.

**Comment by irskep** [comment]
OK, then you should be able to clone literallycanvs's repo, update package.json, and try to install that. If you send me a pull request that works, I will merge it.

**Comment by ahad122** [comment]
The react dependency version on your github repository is correct, 15.1, but incorrect in your NPM repository. In the NPM repository, it's looking for React and React dom version 0.14.6. Please update this. Thank you!

**Comment by irskep** [comment]
Ah. As I said, you can point your package.json to the git repository for now and avoid NPM while you wait for a release.

**Comment by irskep** [comment]
I think this is fixed now.
